### ISSUE TITLE
bank2sf2 hangs when exporting

### ISSUE THREAD

**Issue by dakrk** [Yoshimaster96/mpgc-sound-tools#2]
I'm attempting to use these utilities to export the music from Mario Party 4, and while other tools seem to work fine, I can't seem to get bank2sf2 working.

Just running it on an ID segfaults as it's missing sample WAV files, but I later figured out that `amuse-gui.exe` exports them with the exact file names bank2sf2 is expecting. However, trying to export SF2s provided these files causes it to freeze.

The songs I tested with are 0002 (the MIDI output by dump_msm_sng is the Lottery, but the samples don't seem to match up?), alongside numerous other random ones, and nothing seems to be working.

(Just before submitting this issue, I discovered that it was commit ca730b07eb0c5f361e35f543247e1864e9d57c44 that broke this.)

**Comment by Yoshimaster96** [comment]
Are you sure you're using the correct bank files?

In the example you provided, 0x0002 is the sequence ID, but the group ID is 0x0065 (I assume you found the list [here](https://github.com/Yoshimaster96/mpgc-sound-tools/wiki/Song-List:-Mario-Party-4)).

Try running `bank2sf2 0065` instead and see if that works.

Hope that helps.

**Comment by dakrk** [comment]
Oops, I didn't see that the wiki existed, my bad. 0x0065 is indeed the correct group ID though and exporting that gave the correct instruments, thank you!

**Comment by Yoshimaster96** [comment]
Thanks! Glad I could help!
